"""
Masking Service

Applies visual masks to documents using PyMuPDF (PDF native) or PIL (images).

Two public entry points:

``apply_pdf_masks(pdf_bytes, entities) -> bytes``
    PDF-native redaction via PyMuPDF.  Bounding boxes are normalised [0, 1].
    Handles form widgets (updates field values in place).

``apply_masks(image_path, entities, output_path) -> str``
    Image-based masking via PIL.  Used for PNG/JPG originals; output is saved
    as a PNG.  The caller (MaskingModel) wraps the result in a PDF.

Entity format
-------------
Each entity must have an ``occurrences`` list.  Each occurrence has:
- ``page_number`` (int, 1-indexed)
- ``original_text`` (str, exact text at this location)
- ``bounding_boxes`` (list of [x, y, width, height] — one per line of text,
  normalised 0.0–1.0 relative to page/image dimensions)

Masking strategies
------------------
"Black Out" / "redact"
    Black-filled rectangle.  Original text permanently removed.

"Fake Data" / "fake_name"
    White-filled rectangle with ``replacement_text`` inserted.
    Token-aligned partial name replacement is applied when an occurrence's
    ``original_text`` differs from the entity's canonical ``original_text``
    (e.g. "Stephen" matched to the replacement slice of "Stephen Parrot" →
    "Jane").

"Entity Label" / "entity_label"
    White-filled rectangle with auto label, e.g. ``Full_Name_1``.  Label is
    pre-generated by DocumentIntelligenceModel and stored in
    ``replacement_text``; a fallback counter is used if absent.
"""

import io
import logging
import os
import re
from typing import Any, Dict, List, Optional, Tuple

import fitz  # PyMuPDF
from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger(__name__)


class MaskingService:
    """
    Apply visual masks to documents.

    Instantiate once and reuse across requests (e.g. in MaskingModel.load_context).
    Optionally supply a ``font_path`` to a TrueType font for PIL text rendering;
    if omitted, common system fonts are tried in order (Linux → macOS → Windows).
    """

    _STRATEGY_MAP: Dict[str, str] = {
        "Black Out":    "redact",
        "redact":       "redact",
        "Fake Data":    "fake_name",
        "fake_name":    "fake_name",
        "Entity Label": "entity_label",
        "entity_label": "entity_label",
    }

    def __init__(self, font_path: Optional[str] = None):
        self.font_path = font_path

    # ------------------------------------------------------------------
    # PDF-native masking (PyMuPDF)
    # ------------------------------------------------------------------

    def apply_pdf_masks(
        self,
        pdf_bytes: bytes,
        entities: List[Dict[str, Any]],
    ) -> bytes:
        """
        Apply redactions to PDF bytes and return masked PDF bytes.

        Bounding box values are normalised [0, 1] relative to page dimensions.
        Entities with approved=False are skipped.

        Strategies:
            "Black Out"    — black-filled rectangle, text permanently removed.
            "Fake Data"    — white-filled rectangle, replacement_text inserted.
            "Entity Label" — white-filled rectangle, auto label e.g. Full_Name_1.
        """
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        logger.info(
            "apply_pdf_masks: %d page(s), %d entities (%d approved)",
            len(doc), len(entities), sum(1 for e in entities if e.get("approved", True)),
        )

        label_counters: Dict[str, int] = {}
        consistency_map: Dict[str, str] = {}

        approved = [e for e in entities if e.get("approved", True)]

        # page_idx → list of (entity, bbox, occurrence_original_text)
        by_page: Dict[int, List[tuple]] = {}

        for entity in approved:
            for occ in entity.get("occurrences", []):
                page_idx = occ.get("page_number", 1) - 1
                occ_text = occ.get("original_text", entity.get("original_text", ""))
                for bbox in occ.get("bounding_boxes", []):
                    if len(bbox) == 4:
                        by_page.setdefault(page_idx, []).append((entity, bbox, occ_text))

        for page_idx, page_items in sorted(by_page.items()):
            if page_idx >= len(doc):
                continue

            page = doc[page_idx]
            rotation = page.rotation
            # page.rect gives display (visual) dimensions, accounting for rotation.
            # Drawing ops (add_redact_annot, insert_text) use raw PDF (mediabox)
            # coordinates.  derotation_matrix converts display → raw PDF so that
            # bounding boxes from the vision model (which are in display space)
            # land in the correct position regardless of page rotation.
            W = page.rect.width
            H = page.rect.height
            derot = page.derotation_matrix

            inserts: List[Tuple[fitz.Rect, fitz.Rect, str]] = []  # (raw_rect, display_rect, text)

            # Collect widgets once per page into a plain list so we can
            # safely look them up without re-iterating the live generator.
            page_widgets = list(page.widgets())

            for entity, bbox, occ_original_text in page_items:
                raw_strategy = entity.get("strategy", "redact")
                strategy = self._STRATEGY_MAP.get(raw_strategy, "redact")

                if len(bbox) != 4:
                    continue

                replacement = self._resolve_occurrence_replacement(
                    entity, occ_original_text, strategy, label_counters, consistency_map
                )
                fill_color = (0.0, 0.0, 0.0) if strategy == "redact" else (1.0, 1.0, 1.0)

                x, y, w, h = bbox
                # Compute in display space, then transform to raw PDF coordinates.
                rect_display = fitz.Rect(x * W, y * H, (x + w) * W, (y + h) * H)
                rect = rect_display * derot

                # If this bbox covers a form widget, update the widget
                # value directly instead of painting a redact rect on top.
                # Painting over a widget annotation does not clear it —
                # the widget renders its value on top of whatever is in
                # the content stream, causing the original value to show
                # through.  Updating the value in place avoids that while
                # keeping the form field structure intact.
                #
                # An entity can span multiple form widgets (e.g. day/month/year
                # date fields, or street/suburb address fields).  We collect
                # ALL overlapping widgets and mask each one whose field value
                # appears as a component of occ_original_text.
                overlapping_widgets = [
                    wgt for wgt in page_widgets if not (wgt.rect & rect).is_empty
                ]
                # Fallback: bbox from the vision model may not precisely land on
                # the widget rect (e.g. tight text bbox vs larger widget area).
                # Search by field-value match so we still mask the right widget
                # even when the coordinate intersection test misses.
                if not overlapping_widgets and occ_original_text.strip():
                    target_norm_fb = re.sub(r"\s+", " ", occ_original_text.strip()).lower()
                    for wgt in page_widgets:
                        wval = wgt.field_value or ""
                        if not wval.strip():
                            continue
                        wval_norm = re.sub(r"\s+", " ", wval.strip()).lower()
                        # Match: widget value equals occurrence text, or widget
                        # value is a component of a multi-widget occurrence span,
                        # or occurrence text is fully contained in the widget value.
                        if (wval_norm == target_norm_fb
                                or wval_norm in target_norm_fb
                                or target_norm_fb in wval_norm):
                            overlapping_widgets.append(wgt)
                            logger.debug(
                                "widget value-match fallback: field=%r val=%r occ=%r",
                                wgt.field_name, wval, occ_original_text,
                            )
                if overlapping_widgets:
                    sub = "[MASKED]" if strategy == "redact" else (replacement or "[MASKED]")
                    target = occ_original_text.strip()
                    # Normalise whitespace for substring matching across widgets
                    target_norm = re.sub(r"\s+", " ", target).lower()

                    for overlapping_widget in overlapping_widgets:
                        current_val = overlapping_widget.field_value or ""
                        if not current_val.strip():
                            continue

                        # Try replacing the full occ_original_text within this
                        # widget's value (handles the single-widget case).
                        if target:
                            new_val = current_val.replace(target, sub)
                            if new_val == current_val and target.lower() in current_val.lower():
                                new_val = re.sub(re.escape(target), sub, current_val, flags=re.IGNORECASE)
                        else:
                            new_val = sub

                        if new_val == current_val:
                            # Full target not in this widget — check whether
                            # this widget's value is itself a component of the
                            # occurrence text (multi-widget span, e.g. "31" in
                            # "31 / 7 / 1980").  Replace with aligned slice.
                            val_norm = re.sub(r"\s+", " ", current_val.strip()).lower()
                            if val_norm and val_norm in target_norm:
                                if strategy == "fake_name":
                                    new_val = MaskingService._resolve_component_replacement(
                                        current_val, target, sub,
                                        overlapping_widget.rect, page_widgets,
                                    )
                                else:
                                    new_val = sub

                        if new_val != current_val:
                            overlapping_widget.field_value = new_val
                            overlapping_widget.update()
                else:
                    page.add_redact_annot(rect, fill=fill_color)
                    if replacement:
                        inserts.append((rect, rect_display, replacement))

            page.apply_redactions()

            for rect, rect_display, text in inserts:
                # Use display rect height for font sizing (visually correct scale).
                # Use raw PDF rect for position; rotate to counter page rotation so
                # replacement text appears horizontal in the display view.
                fontsize = max(6, min(36, int(rect_display.height * 0.7)))
                page.insert_text(
                    (rect.x0 + 2, rect.y1 - 2),
                    text,
                    fontsize=fontsize,
                    rotate=rotation,
                )

        buf = io.BytesIO()
        # garbage=4: full cross-reference rebuild — purges all unreferenced
        # objects, including old widget appearance streams that contained the
        # original (sensitive) field values before they were overwritten.
        doc.save(buf, garbage=4, deflate=True)
        doc.close()
        result = buf.getvalue()
        logger.info("apply_pdf_masks complete: output %d bytes", len(result))
        return result

    # ------------------------------------------------------------------
    # Image masking (PIL) — used when original file is PNG/JPG
    # ------------------------------------------------------------------

    def apply_masks(
        self,
        image_path: str,
        entities: List[Dict],
        output_path: str,
        mask_color: Tuple[int, int, int] = (255, 255, 255),
        text_color: Tuple[int, int, int] = (0, 0, 0),
        border_color: Tuple[int, int, int] = (200, 200, 200),
    ) -> str:
        """Apply masks to an image file and save the result."""
        if not os.path.exists(image_path):
            raise FileNotFoundError(f"Image file not found: {image_path}")

        image = Image.open(image_path)
        draw = ImageDraw.Draw(image)
        img_width, img_height = image.size
        logger.info(
            "apply_masks: image %dx%d, %d entities (%d approved)",
            img_width, img_height, len(entities),
            sum(1 for e in entities if e.get("approved", True)),
        )

        label_counters: Dict[str, int] = {}
        consistency_map: Dict[str, str] = {}

        approved = [e for e in entities if e.get("approved", True)]

        for entity in approved:
            raw_strategy = entity.get("strategy", "")
            strategy = self._STRATEGY_MAP.get(raw_strategy, "redact")
            fill = (0, 0, 0) if strategy == "redact" else mask_color

            for occ in entity.get("occurrences", []):
                occ_original_text = occ.get("original_text", entity.get("original_text", ""))
                replacement = self._resolve_occurrence_replacement(
                    entity, occ_original_text, strategy, label_counters, consistency_map
                )
                for bbox in occ.get("bounding_boxes", []):
                    if len(bbox) != 4:
                        continue
                    x, y, width, height = self._normalize_bbox(bbox, img_width, img_height)
                    if width <= 0 or height <= 0:
                        continue
                    draw.rectangle(
                        [x, y, x + width, y + height],
                        fill=fill,
                        outline=border_color,
                        width=1,
                    )
                    if strategy != "redact" and replacement:
                        self._draw_text(draw, replacement, x, y, width, height, text_color)

        image.save(output_path, "PNG", quality=95)
        logger.info("apply_masks complete: saved to %s", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_component_replacement(
        current_val: str,
        original_text: str,
        replacement_text: str,
        widget_rect,
        page_widgets: list,
    ) -> str:
        """
        Return the replacement slice for a widget whose value is a component
        of a multi-widget occurrence span (e.g. "15" within "15/03/1985").

        Strategy
        --------
        1. Separator split — try /, -, ., then whitespace.  If original and
           replacement split into the same number of non-empty parts and
           current_val matches exactly one part → return the aligned part.
           When multiple parts match (e.g. DD==MM=="01") use widget x-position
           to rank among sibling widgets and pick the correct index.

        2. Character-level fallback — strip separators from both sides and
           align by character position, ranked by (y, x) widget reading order.
           Handles 10-widget single-character Medicare numbers etc.

        Falls back to returning replacement_text unchanged on any failure
        (no regression vs. current behaviour).
        """
        current = current_val.strip()
        orig = original_text.strip()
        repl = replacement_text.strip()

        if not current or not orig or not repl:
            return replacement_text

        # --- 1. Separator-based ---
        _sep_candidates: List[Optional[str]] = ['/', '-', '.', None]
        for sep in _sep_candidates:
            if sep is None:
                orig_parts = orig.split()
                repl_parts = repl.split()
            else:
                orig_parts = [p.strip() for p in orig.split(sep) if p.strip()]
                repl_parts = [p.strip() for p in repl.split(sep) if p.strip()]

            if len(orig_parts) < 2 or len(orig_parts) != len(repl_parts):
                continue

            matching = [i for i, p in enumerate(orig_parts) if p.lower() == current.lower()]
            if not matching:
                continue

            if len(matching) == 1:
                return repl_parts[matching[0]]

            # Ambiguous: same value appears in multiple parts.
            # Rank sibling widgets (those whose values match any orig part)
            # left-to-right by x-position and assign parts greedily.
            used: set = set()
            x_to_part: dict = {}
            for wgt in sorted(page_widgets, key=lambda w: w.rect.x0):
                wval = (wgt.field_value or "").strip()
                for i, part in enumerate(orig_parts):
                    if i not in used and wval.lower() == part.lower():
                        x_to_part[round(wgt.rect.x0, 1)] = i
                        used.add(i)
                        break

            wx = round(widget_rect.x0, 1)
            if wx in x_to_part:
                idx = x_to_part[wx]
                if idx < len(repl_parts):
                    return repl_parts[idx]

            # Positional lookup failed — return first matched part
            return repl_parts[matching[0]]

        # --- 2. Character-level fallback ---
        _sep_re = re.compile(r'[\s/\-\.\,]')
        orig_chars = _sep_re.sub('', orig)
        repl_chars = _sep_re.sub('', repl)
        curr_chars = _sep_re.sub('', current)

        if (0 < len(curr_chars) <= 3
                and len(orig_chars) == len(repl_chars)
                and len(orig_chars) > len(curr_chars)):
            # Collect component widgets: those whose stripped values fit within
            # orig_chars, sorted by (y, x) reading order.
            comp_widgets = [
                wgt for wgt in page_widgets
                if 0 < len(_sep_re.sub('', (wgt.field_value or "").strip())) <= 3
                and _sep_re.sub('', (wgt.field_value or "").strip()).lower()
                    in orig_chars.lower()
            ]
            comp_widgets.sort(key=lambda w: (round(w.rect.y0), round(w.rect.x0)))

            # Walk through widgets in order, tracking char position.
            char_pos = 0
            for wgt in comp_widgets:
                wval_stripped = _sep_re.sub('', (wgt.field_value or "").strip())
                wrect = wgt.rect
                if (abs(wrect.x0 - widget_rect.x0) < 2
                        and abs(wrect.y0 - widget_rect.y0) < 2):
                    end = char_pos + len(curr_chars)
                    if end <= len(repl_chars):
                        return repl_chars[char_pos:end]
                    break
                char_pos += len(wval_stripped)

        return replacement_text

    @staticmethod
    def _resolve_occurrence_replacement(
        entity: Dict[str, Any],
        occ_original_text: str,
        strategy: str,
        label_counters: Dict[str, int],
        consistency_map: Dict[str, str],
    ) -> str:
        """
        Derive the replacement text for a single occurrence.

        For occurrences from merged entities the occurrence original_text may
        differ from the entity original_text (e.g. "Stephen" vs "Stephen Parrot").
        The replacement is derived by token-aligning the occurrence against the
        entity's canonical original_text and taking the corresponding slice of
        the entity's replacement_text.

        Falls back to _resolve_replacement for the entity-level text when no
        alignment is found (covers entity_label, Black Out, and exact matches).
        """
        if strategy == "redact":
            return ""

        entity_orig = entity.get("original_text", "").lower().strip()
        occ_orig = occ_original_text.lower().strip()

        # Exact match or no occurrence text — use standard resolution
        if not occ_orig or occ_orig == entity_orig:
            return MaskingService._resolve_replacement(
                entity, strategy, label_counters, consistency_map
            )

        if strategy == "fake_name":
            entity_repl = entity.get("replacement_text", "")
            if not entity_repl:
                return ""
            entity_tokens = entity_orig.split()
            occ_tokens = occ_orig.split()
            # Preserve original casing for the prefix portion of the output
            occ_tokens_cased = occ_original_text.strip().split()
            repl_tokens = entity_repl.split()
            n = len(occ_tokens)
            # Find contiguous window of occ_tokens within entity_tokens
            for k in range(len(entity_tokens) - n + 1):
                if entity_tokens[k:k + n] == occ_tokens and len(repl_tokens) >= k + n:
                    return " ".join(repl_tokens[k:k + n])
            # No contiguous window found — try shared-suffix alignment.
            # e.g. occ="Mr Doe", entity="John Doe" → repl="Jane Smith" → "Mr Smith"
            # Finds the longest matching suffix between occ and entity tokens,
            # then keeps the occ prefix (original casing) and takes the aligned replacement suffix.
            for k in range(min(n, len(entity_tokens)), 0, -1):
                if entity_tokens[-k:] == occ_tokens[-k:] and len(repl_tokens) >= k:
                    prefix_tokens = occ_tokens_cased[:-k]
                    suffix_repl = repl_tokens[-k:]
                    return " ".join(prefix_tokens + suffix_repl)
            # No alignment found — use full replacement
            return entity_repl

        # entity_label: use standard resolution (label is entity-scoped)
        return MaskingService._resolve_replacement(
            entity, strategy, label_counters, consistency_map
        )

    @staticmethod
    def _resolve_replacement(
        entity: Dict[str, Any],
        strategy: str,
        label_counters: Dict[str, int],
        consistency_map: Dict[str, str],
    ) -> str:
        if strategy == "redact":
            return ""

        original_key = entity.get("original_text", "").lower().strip()

        if original_key in consistency_map:
            return consistency_map[original_key]

        if strategy == "fake_name":
            text = entity.get(
                "replacement_text",
                f"[{entity.get('entity_type', 'UNKNOWN')}]",
            )
            consistency_map[original_key] = text
            return text

        if strategy == "entity_label":
            # Respect a label pre-generated by the document intelligence model
            # (stored in replacement_text).  Fall back to generating one here
            # only if no pre-set value is available.
            pre_set = entity.get("replacement_text", "")
            if pre_set:
                consistency_map[original_key] = pre_set
                return pre_set
            etype = (
                entity.get("entity_type", "Unknown")
                .replace(" ", "_")
                .replace("-", "_")
            )
            label_counters[etype] = label_counters.get(etype, 0) + 1
            count = label_counters[etype]
            suffix = chr(64 + count) if count <= 26 else str(count)
            label = f"{etype}_{suffix}"
            consistency_map[original_key] = label
            return label

        return ""

    def _normalize_bbox(
        self, bbox: List[float], img_width: int, img_height: int
    ) -> Tuple[int, int, int, int]:
        x, y, width, height = bbox
        x = int(x * img_width)
        y = int(y * img_height)
        width = int(width * img_width)
        height = int(height * img_height)
        padding = 2
        x = max(0, x - padding)
        y = max(0, y - padding)
        width = min(img_width - x, width + 2 * padding)
        height = min(img_height - y, height + 2 * padding)
        return x, y, width, height

    def _draw_text(self, draw, text, x, y, box_width, box_height, text_color):
        font = self._get_font(box_height)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]

        if text_width > box_width * 0.95:
            font = self._get_font(int(box_height * 0.8))
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]

        text_x = x + (box_width - text_width) // 2
        text_y = y + (box_height - text_height) // 2
        draw.text((text_x, text_y), text, fill=text_color, font=font)

    def _get_font(self, height: int) -> ImageFont.ImageFont:
        font_size = max(8, int(height * 0.7))
        try:
            if self.font_path and os.path.exists(self.font_path):
                return ImageFont.truetype(self.font_path, font_size)
            for path in [
                "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # Linux (Databricks)
                "/System/Library/Fonts/Helvetica.ttc",               # macOS
                "C:\\Windows\\Fonts\\arial.ttf",                     # Windows
            ]:
                if os.path.exists(path):
                    return ImageFont.truetype(path, font_size)
            return ImageFont.load_default()
        except Exception:
            return ImageFont.load_default()
