"""
Masking Service

Applies visual masks to documents using PyMuPDF (PDF native) or PIL (images).

Two public entry points:

``apply_pdf_masks(pdf_bytes, entities) -> bytes``
    PDF-native redaction via PyMuPDF.  Bounding boxes are normalised [0, 1].
    Handles form widgets (updates field values in place).  Accepts both the
    new ``occurrences`` entity format and the old ``bounding_box`` /
    ``bounding_boxes`` format.

``apply_masks(image_path, entities, output_path) -> str``
    Image-based masking via PIL.  Used for PNG/JPG originals; output is saved
    as a PNG.  The caller (MaskingModel) wraps the result in a PDF.

Masking strategies
------------------
"Black Out" / "redact"
    Black-filled rectangle.  Original text permanently removed.

"Fake Data" / "fake_name"
    White-filled rectangle with ``replacement_text`` inserted.
    Token-aligned partial name replacement is applied when an occurrence's
    ``original_text`` differs from the entity's canonical ``original_text``
    (e.g. "Stephen" matched to the replacement slice of "Stephen Parrot" →
    "Jane").

"Entity Label" / "entity_label"
    White-filled rectangle with auto label, e.g. ``Full_Name_1``.  Label is
    pre-generated by DocumentIntelligenceModel and stored in
    ``replacement_text``; a fallback counter is used if absent.
"""

import io
import logging
import os
import re
from typing import Any, Dict, List, Optional, Tuple

import fitz  # PyMuPDF
from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger(__name__)


class MaskingService:
    """
    Apply visual masks to documents.

    Instantiate once and reuse across requests (e.g. in MaskingModel.load_context).
    Optionally supply a ``font_path`` to a TrueType font for PIL text rendering;
    if omitted, common system fonts are tried in order (Linux → macOS → Windows).
    """

    _STRATEGY_MAP: Dict[str, str] = {
        "Black Out":    "redact",
        "redact":       "redact",
        "Fake Data":    "fake_name",
        "fake_name":    "fake_name",
        "Entity Label": "entity_label",
        "entity_label": "entity_label",
    }

    def __init__(self, font_path: Optional[str] = None):
        self.font_path = font_path

    # ------------------------------------------------------------------
    # PDF-native masking (PyMuPDF)
    # ------------------------------------------------------------------

    def apply_pdf_masks(
        self,
        pdf_bytes: bytes,
        entities: List[Dict[str, Any]],
    ) -> bytes:
        """
        Apply redactions to PDF bytes and return masked PDF bytes.

        Bounding box values are normalised [0, 1] relative to page dimensions.
        Entities with approved=False are skipped.

        Strategies:
            "Black Out"    — black-filled rectangle, text permanently removed.
            "Fake Data"    — white-filled rectangle, replacement_text inserted.
            "Entity Label" — white-filled rectangle, auto label e.g. Full_Name_1.
        """
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        logger.info(
            "apply_pdf_masks: %d page(s), %d entities (%d approved)",
            len(doc), len(entities), sum(1 for e in entities if e.get("approved", True)),
        )

        label_counters: Dict[str, int] = {}
        consistency_map: Dict[str, str] = {}

        approved = [e for e in entities if e.get("approved", True)]

        # ------------------------------------------------------------------
        # Build per-page work items.
        #
        # New format: entity has "occurrences" — iterate them directly,
        # deriving replacement_text per occurrence via token alignment.
        #
        # Old format (no occurrences): fall back to bounding_box /
        # bounding_boxes + page_number, using the consistency_map path.
        # ------------------------------------------------------------------
        # page_idx → list of (entity, bbox, occurrence_original_text)
        by_page: Dict[int, List[tuple]] = {}

        old_format: List[Dict[str, Any]] = []
        for entity in approved:
            if entity.get("occurrences"):
                for occ in entity["occurrences"]:
                    page_idx = occ.get("page_number", 1) - 1
                    bbox = occ.get("bounding_box", [])
                    if len(bbox) == 4:
                        by_page.setdefault(page_idx, []).append(
                            (entity, bbox, occ.get("original_text", entity.get("original_text", "")))
                        )
            else:
                old_format.append(entity)

        # Old-format entities: seed consistency map and group by page
        if old_format:
            self._seed_consistency_map(old_format, consistency_map)
            old_by_page: Dict[int, List[Dict[str, Any]]] = {}
            for entity in old_format:
                page_idx = entity.get("page_number", 1) - 1
                old_by_page.setdefault(page_idx, []).append(entity)
            for page_idx in old_by_page:
                old_by_page[page_idx] = self._remove_contained_entities(old_by_page[page_idx])
            for page_idx, ents in old_by_page.items():
                for entity in ents:
                    for bbox in self._resolve_bboxes(entity):
                        by_page.setdefault(page_idx, []).append(
                            (entity, bbox, entity.get("original_text", ""))
                        )

        for page_idx, page_items in sorted(by_page.items()):
            if page_idx >= len(doc):
                continue

            page = doc[page_idx]
            W = page.rect.width
            H = page.rect.height

            inserts: List[Tuple[fitz.Rect, str]] = []

            # Collect widgets once per page into a plain list so we can
            # safely look them up without re-iterating the live generator.
            page_widgets = list(page.widgets())

            for entity, bbox, occ_original_text in page_items:
                raw_strategy = entity.get("strategy", "redact")
                strategy = self._STRATEGY_MAP.get(raw_strategy, "redact")

                if len(bbox) != 4:
                    continue

                replacement = self._resolve_occurrence_replacement(
                    entity, occ_original_text, strategy, label_counters, consistency_map
                )
                fill_color = (0.0, 0.0, 0.0) if strategy == "redact" else (1.0, 1.0, 1.0)

                x, y, w, h = bbox
                rect = fitz.Rect(x * W, y * H, (x + w) * W, (y + h) * H)

                # If this bbox covers a form widget, update the widget
                # value directly instead of painting a redact rect on top.
                # Painting over a widget annotation does not clear it —
                # the widget renders its value on top of whatever is in
                # the content stream, causing the original value to show
                # through.  Updating the value in place avoids that while
                # keeping the form field structure intact.
                overlapping_widget = next(
                    (wgt for wgt in page_widgets if not (wgt.rect & rect).is_empty),
                    None,
                )
                if overlapping_widget is not None:
                    # Form widgets render on top of the page content stream, so
                    # a redact annotation underneath is invisible.  Substitute
                    # only the sensitive substring within the field value to
                    # preserve surrounding context (e.g. labels, other fields).
                    current_val = overlapping_widget.field_value or ""
                    target = occ_original_text.strip()
                    sub = "[MASKED]" if strategy == "redact" else (replacement or "[MASKED]")
                    if target:
                        new_val = current_val.replace(target, sub)
                        if new_val == current_val and target.lower() in current_val.lower():
                            # Case-insensitive fallback
                            new_val = re.sub(re.escape(target), sub, current_val, flags=re.IGNORECASE)
                    else:
                        new_val = sub
                    overlapping_widget.field_value = new_val
                    overlapping_widget.update()
                else:
                    page.add_redact_annot(rect, fill=fill_color)
                    if replacement:
                        inserts.append((rect, replacement))

            page.apply_redactions()

            for rect, text in inserts:
                fontsize = max(6, min(10, int(rect.height * 0.7)))
                page.insert_text(
                    (rect.x0 + 2, rect.y1 - 2),
                    text,
                    fontsize=fontsize,
                )

        buf = io.BytesIO()
        # garbage=4: full cross-reference rebuild — purges all unreferenced
        # objects, including old widget appearance streams that contained the
        # original (sensitive) field values before they were overwritten.
        doc.save(buf, garbage=4, deflate=True)
        doc.close()
        result = buf.getvalue()
        logger.info("apply_pdf_masks complete: output %d bytes", len(result))
        return result

    # ------------------------------------------------------------------
    # Image masking (PIL) — used when original file is PNG/JPG
    # ------------------------------------------------------------------

    def apply_masks(
        self,
        image_path: str,
        entities: List[Dict],
        output_path: str,
        mask_color: Tuple[int, int, int] = (255, 255, 255),
        text_color: Tuple[int, int, int] = (0, 0, 0),
        border_color: Tuple[int, int, int] = (200, 200, 200),
    ) -> str:
        """Apply masks to an image file and save the result."""
        if not os.path.exists(image_path):
            raise FileNotFoundError(f"Image file not found: {image_path}")

        image = Image.open(image_path)
        draw = ImageDraw.Draw(image)
        img_width, img_height = image.size
        logger.info(
            "apply_masks: image %dx%d, %d entities",
            img_width, img_height, len(entities),
        )

        for entity in entities:
            raw_strategy = entity.get("strategy", "")
            strategy = self._STRATEGY_MAP.get(raw_strategy, "redact")
            replacement_text = entity.get("replacement_text", "")
            bboxes = self._resolve_bboxes(entity)

            fill = (0, 0, 0) if strategy == "redact" else mask_color

            for bbox in bboxes:
                if len(bbox) != 4:
                    continue
                x, y, width, height = self._normalize_bbox(bbox, img_width, img_height)

                if width <= 0 or height <= 0:
                    continue

                # Black Out → solid black rectangle, no text
                # Fake Data / Entity Label → white rectangle + replacement text
                draw.rectangle(
                    [x, y, x + width, y + height],
                    fill=fill,
                    outline=border_color,
                    width=1,
                )

                if strategy != "redact" and replacement_text:
                    self._draw_text(draw, replacement_text, x, y, width, height, text_color)

        image.save(output_path, "PNG", quality=95)
        logger.info("apply_masks complete: saved to %s", output_path)
        return output_path

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_bboxes(entity: Dict[str, Any]) -> List[List[float]]:
        multi = entity.get("bounding_boxes")
        if multi:
            result = []
            for b in multi:
                if isinstance(b, (list, tuple)) and len(b) == 4:
                    result.append(list(b))
                elif isinstance(b, dict) and all(k in b for k in ("x", "y", "width", "height")):
                    result.append([b["x"], b["y"], b["width"], b["height"]])
            return result
        single = entity.get("bounding_box")
        if single and len(single) == 4:
            return [list(single)]
        return []

    @staticmethod
    def _resolve_occurrence_replacement(
        entity: Dict[str, Any],
        occ_original_text: str,
        strategy: str,
        label_counters: Dict[str, int],
        consistency_map: Dict[str, str],
    ) -> str:
        """
        Derive the replacement text for a single occurrence.

        For occurrences from merged entities the occurrence original_text may
        differ from the entity original_text (e.g. "Stephen" vs "Stephen Parrot").
        The replacement is derived by token-aligning the occurrence against the
        entity's canonical original_text and taking the corresponding slice of
        the entity's replacement_text.

        Falls back to _resolve_replacement for the entity-level text when no
        alignment is found (covers entity_label, Black Out, and exact matches).
        """
        if strategy == "redact":
            return ""

        entity_orig = entity.get("original_text", "").lower().strip()
        occ_orig = occ_original_text.lower().strip()

        # Exact match or no occurrence text — use standard resolution
        if not occ_orig or occ_orig == entity_orig:
            return MaskingService._resolve_replacement(
                entity, strategy, label_counters, consistency_map
            )

        if strategy == "fake_name":
            entity_repl = entity.get("replacement_text", "")
            if not entity_repl:
                return ""
            entity_tokens = entity_orig.split()
            occ_tokens = occ_orig.split()
            repl_tokens = entity_repl.split()
            n = len(occ_tokens)
            # Find contiguous window of occ_tokens within entity_tokens
            for k in range(len(entity_tokens) - n + 1):
                if entity_tokens[k:k + n] == occ_tokens and len(repl_tokens) >= k + n:
                    return " ".join(repl_tokens[k:k + n])
            # No contiguous window found — try shared-suffix alignment.
            # e.g. occ="Mr Doe", entity="John Doe" → repl="Jane Smith" → "Mr Smith"
            # Finds the longest matching suffix between occ and entity tokens,
            # then keeps the occ prefix as-is and takes the aligned replacement suffix.
            for k in range(min(n, len(entity_tokens)), 0, -1):
                if entity_tokens[-k:] == occ_tokens[-k:] and len(repl_tokens) >= k:
                    prefix_tokens = occ_tokens[:-k]
                    suffix_repl = repl_tokens[-k:]
                    return " ".join(prefix_tokens + suffix_repl)
            # No alignment found — use full replacement
            return entity_repl

        # entity_label: use standard resolution (label is entity-scoped)
        return MaskingService._resolve_replacement(
            entity, strategy, label_counters, consistency_map
        )

    @staticmethod
    def _resolve_replacement(
        entity: Dict[str, Any],
        strategy: str,
        label_counters: Dict[str, int],
        consistency_map: Dict[str, str],
    ) -> str:
        if strategy == "redact":
            return ""

        original_key = entity.get("original_text", "").lower().strip()

        if original_key in consistency_map:
            return consistency_map[original_key]

        if strategy == "fake_name":
            text = entity.get(
                "replacement_text",
                f"[{entity.get('entity_type', 'UNKNOWN')}]",
            )
            consistency_map[original_key] = text
            return text

        if strategy == "entity_label":
            # Respect a label pre-generated by the document intelligence model
            # (stored in replacement_text).  Fall back to generating one here
            # only if no pre-set value is available.
            pre_set = entity.get("replacement_text", "")
            if pre_set:
                consistency_map[original_key] = pre_set
                return pre_set
            etype = (
                entity.get("entity_type", "Unknown")
                .replace(" ", "_")
                .replace("-", "_")
            )
            label_counters[etype] = label_counters.get(etype, 0) + 1
            count = label_counters[etype]
            suffix = chr(64 + count) if count <= 26 else str(count)
            label = f"{etype}_{suffix}"
            consistency_map[original_key] = label
            return label

        return ""

    def _normalize_bbox(
        self, bbox: List[float], img_width: int, img_height: int
    ) -> Tuple[int, int, int, int]:
        x, y, width, height = bbox
        x = int(x * img_width)
        y = int(y * img_height)
        width = int(width * img_width)
        height = int(height * img_height)
        padding = 2
        x = max(0, x - padding)
        y = max(0, y - padding)
        width = min(img_width - x, width + 2 * padding)
        height = min(img_height - y, height + 2 * padding)
        return x, y, width, height

    def _draw_text(self, draw, text, x, y, box_width, box_height, text_color):
        font = self._get_font(box_height)
        bbox = draw.textbbox((0, 0), text, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]

        if text_width > box_width * 0.95:
            font = self._get_font(int(box_height * 0.8))
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]

        text_x = x + (box_width - text_width) // 2
        text_y = y + (box_height - text_height) // 2
        draw.text((text_x, text_y), text, fill=text_color, font=font)

    def _seed_consistency_map(
        self,
        entities: List[Dict[str, Any]],
        consistency_map: Dict[str, str],
    ) -> None:
        """
        Pre-populate consistency_map so that partial name variants inherit
        their replacement from the corresponding full-name entity.

        Process longest original_text first so that full names are mapped
        before their subsets are encountered.  For each shorter entity,
        find a contiguous token window in a longer mapped entry and take
        the aligned replacement tokens.

        Examples:
            "John Michael Smith" → "Jane Alice Doe"
            "John"               → "Jane"       (token 0)
            "Michael"            → "Alice"      (token 1)
            "John Michael"       → "Jane Alice" (tokens 0–1)
            "Michael Smith"      → "Alice Doe"  (tokens 1–2)
            "John Smith"         → own replacement (not contiguous — safe fallback)
        """
        fake_entities = [
            e for e in entities
            if self._STRATEGY_MAP.get(e.get("strategy", ""), "") == "fake_name"
            and e.get("replacement_text")
            and e.get("original_text")
        ]
        # Sort longest-first so full names seed the map before subsets
        fake_entities.sort(key=lambda e: len(e["original_text"]), reverse=True)

        for entity in fake_entities:
            key = entity["original_text"].lower().strip()
            if key not in consistency_map:
                consistency_map[key] = entity["replacement_text"]

        # Second pass: resolve subsets against already-mapped full names.
        # For each entity, look for a longer entry whose tokens contain the
        # entity's tokens as a contiguous slice, then take the aligned
        # replacement tokens.  Falls back to the entity's own replacement
        # if no contiguous match is found.
        full_name_entries = list(consistency_map.items())  # snapshot
        for entity in fake_entities:
            key = entity["original_text"].lower().strip()
            orig_tokens = key.split()
            n = len(orig_tokens)
            for full_key, full_replacement in full_name_entries:
                if full_key == key:
                    continue  # skip self-match
                full_tokens = full_key.split()
                if len(full_tokens) <= n:
                    continue  # not longer — can't be a superset
                repl_tokens = full_replacement.split()
                if len(repl_tokens) < len(full_tokens):
                    continue  # replacement token count mismatch — skip to avoid misalignment
                # Find contiguous window match
                for i in range(len(full_tokens) - n + 1):
                    if full_tokens[i:i + n] == orig_tokens:
                        consistency_map[key] = " ".join(repl_tokens[i:i + n])
                        break
                else:
                    continue  # no window matched — try next full-name entry
                break  # matched — stop searching

    @staticmethod
    def _remove_contained_entities(
        entities: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Remove entities whose first bounding box is substantially contained
        within a larger entity's bounding box on the same page.

        An entity is considered contained if its bbox overlaps ≥80 % of its
        own area with a larger entity's bbox.
        """
        def _first_bbox(e):
            bboxes = MaskingService._resolve_bboxes(e)
            return bboxes[0] if bboxes else None

        def _area(bbox):
            return bbox[2] * bbox[3]

        def _intersection_area(a, b):
            ax, ay, aw, ah = a
            bx, by, bw, bh = b
            ix = max(ax, bx)
            iy = max(ay, by)
            iw = min(ax + aw, bx + bw) - ix
            ih = min(ay + ah, by + bh) - iy
            if iw <= 0 or ih <= 0:
                return 0.0
            return iw * ih

        # Sort by area descending so larger entities come first
        indexed = [(e, _first_bbox(e)) for e in entities]
        indexed.sort(key=lambda t: _area(t[1]) if t[1] else 0, reverse=True)

        kept = []
        kept_bboxes = []
        for entity, bbox in indexed:
            if bbox is None:
                kept.append(entity)
                continue
            entity_area = _area(bbox)
            contained = any(
                entity_area > 0
                and _intersection_area(bbox, kb) / entity_area >= 0.80
                and _area(kb) > entity_area
                for kb in kept_bboxes
            )
            if not contained:
                kept.append(entity)
                kept_bboxes.append(bbox)
        return kept

    def _get_font(self, height: int) -> ImageFont.ImageFont:
        font_size = max(8, int(height * 0.7))
        try:
            if self.font_path and os.path.exists(self.font_path):
                return ImageFont.truetype(self.font_path, font_size)
            for path in [
                "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # Linux (Databricks)
                "/System/Library/Fonts/Helvetica.ttc",               # macOS
                "C:\\Windows\\Fonts\\arial.ttf",                     # Windows
            ]:
                if os.path.exists(path):
                    return ImageFont.truetype(path, font_size)
            return ImageFont.load_default()
        except Exception:
            return ImageFont.load_default()
